return {
	"nvim-treesitter/nvim-treesitter",
	opts = {
		highlight = { enable = true },
		indent = { enable = true },
		ensure_installed = {
			"awk",
			"bash",
			"c",
			"cmake",
			"comment",
			"diff",
			"dockerfile",
			"git_config",
			"git_rebase",
			"gitattributes",
			"gitcommit",
			"gitignore",
			"html",
			"http",
			"javascript",
			"jq",
			"jsdoc",
			"json",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"nix",
			"pem",
			"printf",
			"python",
			"query",
			"regex",
			"rust",
			"ssh_config",
			"tmux",
			"toml",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"xml",
			"yaml",
		},
		-- incremental_selection = {
		-- 	enable = true,
		-- 	keymaps = {
		-- 		init_selection = "<C-space>",
		-- 		node_incremental = "<C-space>",
		-- 		scope_incremental = false,
		-- 		node_decremental = "<bs>",
		-- 	},
		-- },
	},
}
